# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码')),
                ('webchat', models.CharField(blank=True, max_length=20, null=True, verbose_name='微信')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '系统用户表',
                'db_table': 'angularpy_users',
                'verbose_name_plural': '系统用户表',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
