# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True, verbose_name='远程用户名')),
                ('password', models.CharField(max_length=30, null=True, verbose_name='远程密码')),
                ('port', models.CharField(max_length=10, verbose_name='连接端口')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产用户总表',
                'db_table': 'cmdb_AssetUser',
                'verbose_name_plural': '资产用户总表',
                'ordering': ['username', 'date_created'],
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='机房名称')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='机房地址')),
                ('tel', models.CharField(blank=True, max_length=30, null=True, verbose_name='机房电话')),
                ('contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='机房联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='联系人电话')),
                ('intranet', models.CharField(blank=True, max_length=50, null=True, verbose_name='内网IP范围')),
                ('extranet', models.CharField(blank=True, max_length=50, null=True, verbose_name='外网IP范围')),
                ('operator', models.CharField(blank=True, max_length=32, verbose_name='维护商')),
                ('bandwidth', models.CharField(blank=True, max_length=30, null=True, verbose_name='接入带宽')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'IDC总表',
                'db_table': 'cmdb_IDC',
                'verbose_name_plural': 'IDC总表',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServerAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='主机名')),
                ('cabinet_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜编号')),
                ('cabinet_pos', models.IntegerField(blank=True, null=True, verbose_name='机柜位置')),
                ('status', models.CharField(choices=[('In use', '使用中'), ('Out of use', '未使用'), ('fault', '故障'), ('other', '其他')], default='In use', max_length=10)),
                ('type', models.CharField(choices=[('Server', '物理机'), ('VM', '虚拟机'), ('Docker', '容器'), ('Storage', '存储')], default='Server', max_length=10)),
                ('product_serial', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备序列号')),
                ('product_uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备UUID')),
                ('machine', models.CharField(blank=True, max_length=10, null=True, verbose_name='架构')),
                ('processor_type', models.CharField(blank=True, max_length=80, null=True, verbose_name='CPU类型')),
                ('processor_count', models.IntegerField(blank=True, default=1, null=True, verbose_name='CPU数量')),
                ('processor_core', models.IntegerField(blank=True, default=1, null=True, verbose_name='CPU核心数')),
                ('disks_total_capacity', models.CharField(blank=True, max_length=10, null=True, verbose_name='磁盘总大小')),
                ('disks', models.CharField(blank=True, max_length=100, null=True, verbose_name='磁盘信息')),
                ('node', models.CharField(blank=True, max_length=20, null=True, verbose_name='节点名称')),
                ('bits', models.CharField(blank=True, max_length=5, null=True, verbose_name='系统位数')),
                ('kernel', models.CharField(blank=True, max_length=15, null=True, verbose_name='内核版本')),
                ('swap_total', models.CharField(blank=True, max_length=20, null=True, verbose_name='swap总和')),
                ('swap_free', models.CharField(blank=True, max_length=20, null=True, verbose_name='swap剩余')),
                ('mem_total', models.CharField(blank=True, max_length=20, null=True, verbose_name='内存')),
                ('mem_free', models.CharField(blank=True, max_length=20, null=True, verbose_name='内存空闲')),
                ('os', models.CharField(blank=True, max_length=10, null=True, verbose_name='系统类型')),
                ('distribution', models.CharField(blank=True, max_length=20, null=True, verbose_name='发行版本')),
                ('mounts_num', models.IntegerField(default=1, verbose_name='分区数量')),
                ('mounts', models.CharField(blank=True, max_length=200, null=True, verbose_name='分区信息')),
                ('gateway', models.CharField(blank=True, max_length=50, null=True, verbose_name='网关')),
                ('macaddr', models.CharField(blank=True, max_length=50, null=True, verbose_name='网卡MAC地址')),
                ('ipv4_intranet', models.CharField(blank=True, max_length=50, null=True, verbose_name='ipv4内网IP')),
                ('ipv4_extranet', models.CharField(max_length=50, null=True, verbose_name='ipv4外网IP')),
                ('ipv6_intranet', models.CharField(blank=True, max_length=100, null=True, verbose_name='ipv6内网IP')),
                ('ipv6_extranet', models.CharField(max_length=100, null=True, verbose_name='ipv6外网IP')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.AssetUser', verbose_name='远程登录凭证')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDC', verbose_name='IDC')),
            ],
            options={
                'verbose_name': '服务器资产总表',
                'db_table': 'cmdb_ServerAsset',
                'verbose_name_plural': '服务器资产总表',
                'ordering': ['hostname'],
            },
        ),
    ]
