# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetuser',
            name='port',
        ),
        migrations.AddField(
            model_name='serverasset',
            name='port',
            field=models.IntegerField(default=22, verbose_name='远程连接端口'),
        ),
    ]
