# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170928_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetuser',
            name='create_by',
            field=models.CharField(blank=True, max_length=32, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='idc',
            name='create_by',
            field=models.CharField(blank=True, max_length=32, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='serverasset',
            name='create_by',
            field=models.CharField(blank=True, max_length=32, verbose_name='创建者'),
        ),
    ]
