# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20170930_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverasset',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='assetuser',
            name='password',
            field=models.CharField(max_length=30, null=True, verbose_name='远程用户密码'),
        ),
    ]
