# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20171006_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverasset',
            name='vendor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='供应商'),
        ),
    ]
